# Generated by Django 4.2.30 on 2026-07-16 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Номи муассиса')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Директор')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Рақами телефон')),
                ('type', models.CharField(choices=[('Мактаб', 'Мактаб'), ('Литсей', 'Литсей'), ('Лицей', 'Лицей'), ('Кӯдакистон', 'Кӯдакистон'), ('Идораи маориф', 'Идораи маориф')], default='Мактаб', max_length=50, verbose_name='Намуд')),
                ('language', models.CharField(choices=[('Тоҷикӣ', 'Тоҷикӣ'), ('Ӯзбекӣ', 'Ӯзбекӣ'), ('Русӣ', 'Русӣ')], default='Тоҷикӣ', max_length=50, verbose_name='Забон')),
            ],
            options={
                'verbose_name': 'Муассиса',
                'verbose_name_plural': 'Муассисаҳо',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Раиси маориф'), ('principal', 'Директори муассиса'), ('teacher', 'Муаллим')], default='teacher', max_length=50, verbose_name='Рол')),
                ('assigned_class', models.CharField(blank=True, max_length=20, verbose_name='Синфи вобаста')),
                ('assigned_subject', models.CharField(blank=True, max_length=100, verbose_name='Фани вобаста')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.school', verbose_name='Муассиса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Профили корбар',
                'verbose_name_plural': 'Профилҳои корбар',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ном')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Фан')),
                ('experience', models.CharField(blank=True, max_length=50, verbose_name='Таҷриба')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Тоифа')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Синн')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('education', models.CharField(blank=True, max_length=255, verbose_name='Маълумот')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Акс')),
                ('is_teacher', models.BooleanField(default=True, verbose_name='Муаллим?')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school', verbose_name='Муассиса')),
            ],
            options={
                'verbose_name': 'Муаллим',
                'verbose_name_plural': 'Муаллимон',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Рамзи ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ному насаб')),
                ('class_name', models.CharField(max_length=20, verbose_name='Синф')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school', verbose_name='Муассиса')),
            ],
            options={
                'verbose_name': 'Хонанда',
                'verbose_name_plural': 'Хонандагон',
                'ordering': ['school', 'class_name', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Фан')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Хол')),
                ('period', models.CharField(default='Холҳои ҷорӣ (Онлайн)', max_length=100, verbose_name='Давра')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Сана')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student', verbose_name='Хонанда')),
            ],
            options={
                'verbose_name': 'Хол',
                'verbose_name_plural': 'Холҳо',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuarterGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='Синф')),
                ('subject', models.CharField(max_length=100, verbose_name='Фан')),
                ('quarter', models.IntegerField(choices=[(0, 'Аттестатсия'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Чорак')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Хол')),
                ('att_grade', models.IntegerField(blank=True, null=True, verbose_name='Холи атт.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student', verbose_name='Хонанда')),
            ],
            options={
                'verbose_name': 'Холи чорак',
                'verbose_name_plural': 'Холҳои чорак',
                'unique_together': {('student', 'class_name', 'subject', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='Синф')),
                ('subject', models.CharField(max_length=100, verbose_name='Фан')),
                ('is_default', models.BooleanField(default=False, verbose_name='Стандарт?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол?')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school', verbose_name='Муассиса')),
            ],
            options={
                'verbose_name': 'Фани синф',
                'verbose_name_plural': 'Фанҳои синф',
                'unique_together': {('school', 'class_name', 'subject')},
            },
        ),
    ]
