# Generated by Django 6.0.7 on 2026-07-23 16:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsubject',
            options={'verbose_name': 'Фани синф', 'verbose_name_plural': 'Фанҳои синфӣ'},
        ),
        migrations.AlterModelOptions(
            name='quartergrade',
            options={'verbose_name': 'Холи чоряк', 'verbose_name_plural': 'Холҳои чорякӣ'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'Муассисаи таълимӣ', 'verbose_name_plural': 'Муассисаҳои таълимӣ'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name': 'Муаллим ё кадр', 'verbose_name_plural': 'Муаллимон ва кадрҳо'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профили корбар', 'verbose_name_plural': 'Профилҳои корбарон'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Сана'),
        ),
        migrations.CreateModel(
            name='QuarterLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='Синф')),
                ('subject', models.CharField(max_length=100, verbose_name='Фан')),
                ('quarter', models.IntegerField(choices=[(0, 'Аттестатсия'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Чорак')),
                ('locked', models.BooleanField(default=True, verbose_name='Баста шудааст')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Санаи бастан')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school', verbose_name='Муассиса')),
            ],
            options={
                'verbose_name': 'Бастани чоряк',
                'verbose_name_plural': 'Бастани чорякҳо',
                'ordering': ['-locked_at'],
                'unique_together': {('school', 'class_name', 'subject', 'quarter')},
            },
        ),
    ]
