# Generated by Django 6.0.7 on 2026-08-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_classsubject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='attendance',
            field=models.CharField(blank=True, choices=[('+', '+ (босабаб)'), ('-', '- (бесабаб)')], max_length=10, null=True, verbose_name='Давомат'),
        ),
        migrations.AddField(
            model_name='grade',
            name='behavior_score',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Хулқ-атвор'),
        ),
    ]
