# Generated by Django 4.2.30 on 2026-08-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_teacher_options_classsubject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('Мактаб', 'Мактаб'), ('Литсей', 'Литсей'), ('Лицей', 'Лицей'), ('Муассисаи давлатии таълимии томактабӣ', 'Муассисаи давлатии таълимии томактабӣ'), ('Идораи маориф', 'Идораи маориф')], default='Мактаб', max_length=50, verbose_name='Намуд'),
        ),
    ]
