# Generated by Django 6.0.7 on 2026-08-19 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_school_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ному насаб')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маълумот')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ихтисос')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school', verbose_name='Муассиса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Профили омӯзгор',
                'verbose_name_plural': 'Профилҳои омӯзгорон',
            },
        ),
    ]
