# Generated by Django 4.2.30 on 2026-08-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='allocated_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_subjects', to='portal.teacherprofile', verbose_name='Омӯзгори масъул'),
        ),
    ]
