# Generated by Django 4.2.30 on 2026-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_classsubject_allocated_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='sticker',
            field=models.CharField(blank=True, choices=[('⭐', 'Ситора'), ('☀️', 'Офтобак'), ('🌸', 'Гул'), ('📖', 'Китоб')], max_length=10, null=True, verbose_name='Стикер'),
        ),
    ]
