# Generated by Django 6.0.7 on 2026-09-09 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_clean_duplicate_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDeactivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Санаи дархост')),
                ('status', models.CharField(choices=[('pending', 'Дар тайёри'), ('approved', 'Тасдиқ шуд'), ('rejected', 'Рад шуд')], default='pending', max_length=20, verbose_name='Ҳолат')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Санаи баррасӣ')),
                ('notes', models.TextField(blank=True, verbose_name='Эзоҳ')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.classsubject', verbose_name='Фани синф')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Дархосткунанда')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deactivations', to=settings.AUTH_USER_MODEL, verbose_name='Баррасикунанда')),
            ],
            options={
                'verbose_name': 'Дархости хориҷкунии фан',
                'verbose_name_plural': 'Дархостҳои хориҷкунии фан',
                'ordering': ['-requested_at'],
            },
        ),
    ]
