# Generated by Django 4.2.30 on 2026-09-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_subjectdeactivationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мард / Писар'), ('F', 'Зан / Духтар')], db_index=True, max_length=1, null=True, verbose_name='Ҷинс'),
        ),
    ]
