# Generated by Django 4.2.30 on 2026-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Писар'), ('F', 'Духтар')], db_index=True, max_length=1, null=True, verbose_name='Ҷинс'),
        ),
    ]
