# Generated by Django 4.2.30 on 2026-09-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Сана')),
                ('lesson_number', models.PositiveSmallIntegerField(default=1, verbose_name='Рақами дарс')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Мавзӯъ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.classsubject')),
            ],
            options={
                'ordering': ['-date', 'lesson_number'],
                'unique_together': {('class_subject', 'date', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Сана')),
                ('quarter', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Чорак')),
                ('category', models.CharField(choices=[('current', 'Ҷорӣ'), ('control', 'Назорат')], max_length=20, verbose_name='Категория')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рақам')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Ном')),
                ('is_ajm', models.BooleanField(default=False, verbose_name='АҶМ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.classsubject')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.assessment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.lesson'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['class_subject', 'quarter', 'category'], name='portal_asse_class_s_cc2b59_idx'),
        ),
    ]
