# Generated by Django 4.2.30 on 2026-09-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_lesson_assessment_grade_assessment_grade_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='components',
            field=models.JSONField(blank=True, null=True, verbose_name='Ҷузъҳо'),
        ),
    ]
