# Generated by Django 6.0.7 on 2026-09-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_grade_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='purpose',
            field=models.CharField(blank=True, choices=[('diagnostic', 'Арзёбии ташхисӣ'), ('formative', 'Арзёбии ташаккулдиҳанда'), ('summative', 'Арзёбии ҷамъбастӣ')], default='', max_length=20, verbose_name='Мақсад'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='summative_scope',
            field=models.CharField(blank=True, choices=[('none', '—'), ('intermediate', 'Миёна'), ('final', 'Ниҳоӣ'), ('quarter', 'Чоряк'), ('semester', 'Нимсола'), ('annual', 'Солона'), ('attestation', 'Аттестатсия')], default='none', max_length=20, verbose_name='Доираи ҷамъбастӣ'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='work_type',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Навъи кор'),
        ),
        migrations.AddField(
            model_name='grade',
            name='points_achieved',
            field=models.FloatField(blank=True, null=True, verbose_name='Холҳои гирифташуда'),
        ),
        migrations.AddField(
            model_name='grade',
            name='points_possible',
            field=models.FloatField(blank=True, null=True, verbose_name='Холҳои имконпазир'),
        ),
    ]
