# Generated by Django 6.0.7 on 2026-09-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_assessment_purpose_assessment_summative_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Соат дар ҳафта'),
        ),
    ]
