# Generated by Django 4.2.30 on 2026-09-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_classsubject_hours_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Гурӯҳ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол?')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='portal.classsubject', verbose_name='Фани синф')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to='portal.teacherprofile', verbose_name='Омӯзгор')),
            ],
            options={
                'verbose_name': 'Гурӯҳи таълимӣ',
                'verbose_name_plural': 'Гурӯҳҳои таълимӣ',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='portal.classsubject', verbose_name='Фани синф')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='portal.teachinggroup', verbose_name='Гурӯҳ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_group_memberships', to='portal.student', verbose_name='Хонанда')),
            ],
            options={
                'verbose_name': 'Узвияти гурӯҳӣ',
                'verbose_name_plural': 'Узвиятҳои гурӯҳӣ',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='portal.teachinggroup', verbose_name='Гурӯҳ'),
        ),
        migrations.AddConstraint(
            model_name='teachinggroup',
            constraint=models.UniqueConstraint(fields=('class_subject', 'label'), name='unique_teaching_group_label'),
        ),
        migrations.AddConstraint(
            model_name='subjectgroupmembership',
            constraint=models.UniqueConstraint(fields=('class_subject', 'student'), name='unique_group_membership_per_subject'),
        ),
    ]
