# Generated by Django 4.2.30 on 2026-09-23 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0017_teachinggroup_subjectgroupmembership_lesson_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Фан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Эҷодкарда')),
            ],
            options={
                'verbose_name': 'Фан (реестр)',
                'verbose_name_plural': 'Реестри фанҳо',
            },
        ),
        migrations.CreateModel(
            name='SubjectAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Синф')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_availabilities', to='portal.school', verbose_name='Муассиса')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='portal.subject', verbose_name='Фан')),
            ],
            options={
                'verbose_name': 'Дастрасии фан',
                'verbose_name_plural': 'Дастрасии фанҳо',
            },
        ),
    ]
