# Generated by Django 4.2.30 on 2026-09-24 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0018_subject_subjectavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Номи корбар')),
                ('date', models.DateField(db_index=True, verbose_name='Сана')),
                ('category', models.CharField(choices=[('staff', 'Корманди маориф'), ('director', 'Раиси маориф'), ('principal', 'Директори муассиса'), ('zavuch', 'Завуч'), ('teacher', 'Муаллим'), ('parent_student', 'Волид/хонанда')], max_length=20, verbose_name='Категория')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Миқдори воридшавӣ')),
                ('first_seen', models.DateTimeField(verbose_name='Аввалин фаъолият')),
                ('last_seen', models.DateTimeField(verbose_name='Охирин фаъолият')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.school', verbose_name='Муассиса')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Фаъолияти ҳаррӯза',
                'verbose_name_plural': 'Фаъолияти ҳаррӯза',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'school'], name='portal_dail_date_aae3fa_idx'), models.Index(fields=['date', 'category'], name='portal_dail_date_2045dd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyactivity',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='dailyactivity_user_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('date',), name='dailyactivity_anon_date'),
        ),
    ]
