# Generated by Django 4.2.30 on 2026-10-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_dailyactivity_dailyactivity_dailyactivity_user_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='custom_password_set',
            field=models.BooleanField(default=False, verbose_name='Рамзи шахсӣ таъин шуд'),
        ),
    ]
